### ISSUE TITLE
node.js http-proxy-middleware seems not working

### ISSUE THREAD

**Issue by freerider7777** [nginx/unit#274]
I'm trying to use 
http-proxy-middleware
for some endpoints

and a simple example from here (replacing http->unit-http) does not work:
https://www.npmjs.com/package/http-proxy-middleware
(uses http-proxy inside)

app.js:

```
#!/usr/bin/env node

const {
  createServer,
  IncomingMessage,
  ServerResponse,
} = require('unit-http');

var proxy = require('http-proxy-middleware');

require('http').ServerResponse = ServerResponse;
require('http').IncomingMessage = IncomingMessage;

const express = require('express')
const app = express();


app.get('/', (req, res) => {
    console.log('request /'); // Print the HTML for the Google homepage.
	res.send('Hello, Unit!')
});
 // app.get('/authenticate', (req, res) => res.send('Hello, Unit (authenticate)!'))

app.use('/api', proxy({ target: 'http://www.example.org', changeOrigin: true }))
createServer(app).listen();

```

Error (when calling /api):

TypeError: (options.buffer || req).pipe is not a function
    at Array.stream (/modules/proxy/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:168:29)
    at ProxyServer.<anonymous> (/modules/proxy/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
    at middleware (/modules/proxy/node_modules/http-proxy-middleware/lib/index.js:46:13)
    at Layer.handle [as handle_request] (/modules/proxy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/modules/proxy/node_modules/express/lib/router/index.js:317:13)
    at /modules/proxy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/modules/proxy/node_modules/express/lib/router/index.js:335:12)
    at next (/modules/proxy/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/modules/proxy/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/modules/proxy/node_modules/express/lib/router/layer.js:95:5)
[HPM] Error occurred while trying to proxy request /apiapi from localhost:8080 to http://www.example.org (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
2019/07/05 12:01:10 [notice] 1#1 process 1181 exited with code 0

**Comment by freerider7777** [comment]
Is there a suggested workaround?

**Comment by VBart** [comment]
@freerider7777 The http-proxy uses stream API that isn't currently implemented in unit-http module. Sorry, I don't know what else we can do here except proper implementation of stream API in unit-http. This task is put in todo list for upcoming releases. Thanks for noticing.

**Comment by freerider7777** [comment]
Thanks! I'm glad that you continue development for seamless integration of node to unit.

**Comment by freerider7777** [comment]
Was this fixed in 1.10?

**Comment by VBart** [comment]
@freerider7777 Unfortunately, but no, the "stream" API is still not implemented at the moment. As soon as it will be implemented, the relevant commit will close this ticket.

**Comment by wujjpp** [comment]
@VBart  implement  stream.readable for requset and stream.writable for response in nodejs are really necessary, now we have stopping  integrate unit in our web app based on nodejs

**Comment by VBart** [comment]
@wujjpp Ok. We will consider prioritizing of this issue.
