### ISSUE TITLE
Intermittent `Waiting for control socket to be removed...` after unit reconfiguration

### ISSUE THREAD

**Issue by cgearing** [nginx/unit#610]
Hi,

I've noticed since moving from threaded to multiprocess nginx-unit with python 3.9 I frequently get a loop of `Waiting for control socket to be removed` after the container starts up.

The nginx-unit config:

```
{
    "listeners": {
        "*:8099": {
            "pass": "applications/fastapi"
        }
    },
    "access_log": "/dev/stdout",
    "applications": {
        "fastapi": {
            "processes": 4,
            "limits": {
                "requests": 200
            },
            "type": "python 3.9",
            "path": "/app",
            "module": "main",
            "home": "/usr/local",
            "callable": "app",
            "protocol": "asgi",
        }
    }
}
``` 

Logs from the container:

```
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, launching Unit daemon to perform initial configuration...
prod_web_1          | 2021/11/30 11:07:58 [info] 14#14 unit started
prod_web_1          | 2021/11/30 11:07:58 [info] 17#17 discovery started
Notice: d_web_1          | 2021/11/30 11:07:58 [notice] 17#17 module: python 3.9.9 "/usr/lib/unit/modules/python3.unit.so"
prod_web_1          | 2021/11/30 11:07:58 [info] 15#15 controller started
prod_web_1          | 2021/11/30 11:07:58 [info] 19#19 router started
Notice: d_web_1          | 2021/11/30 11:07:58 [notice] 15#15 process 17 exited with code 0
prod_web_1          | 2021/11/30 11:07:58 [info] 19#19 OpenSSL 1.1.1k  25 Mar 2021, 101010bf
prod_web_1          | {
prod_web_1          | 	"certificates": {},
prod_web_1          | 	"config": {
prod_web_1          | 		"listeners": {},
prod_web_1          | 		"applications": {}
prod_web_1          | 	}
prod_web_1          | }
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Looking for certificate bundles in /docker-entrypoint.d/...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Looking for configuration snippets in /docker-entrypoint.d/...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Applying configuration /docker-entrypoint.d/config.json
prod_web_1          | 2021/11/30 11:07:58 [info] 23#23 "fastapi" prototype started
prod_web_1          | 2021/11/30 11:07:58 [info] 24#24 "fastapi" application started
prod_web_1          | 2021/11/30 11:07:59 [info] 29#29 "fastapi" application started
prod_web_1          | 2021/11/30 11:08:00 [info] 34#34 "fastapi" application started
prod_web_1          | 2021/11/30 11:08:00 [info] 39#39 "fastapi" application started
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: OK: HTTP response status code is '200'
prod_web_1          | {
prod_web_1          | 	"success": "Reconfiguration done."
prod_web_1          | }
prod_web_1          | 
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Stopping Unit daemon after initial configuration...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
Notice: d_web_1          | 2021/11/30 11:08:01 [notice] 15#15 process 18 exited with code 0
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
Notice: d_web_1          | 2021/11/30 11:08:01 [notice] 23#23 app process (isolated 34) exited with code 0
prod_web_1          | 2021/11/30 11:08:01 [alert] 23#23 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
Notice: d_web_1          | 2021/11/30 11:08:01 [notice] 23#23 app process (isolated 24) exited with code 0
prod_web_1          | 2021/11/30 11:08:01 [alert] 23#23 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
Notice: d_web_1          | 2021/11/30 11:08:01 [notice] 23#23 app process (isolated 29) exited with code 0
prod_web_1          | 2021/11/30 11:08:01 [alert] 23#23 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
Notice: d_web_1          | 2021/11/30 11:08:01 [notice] 23#23 app process (isolated 39) exited with code 0
prod_web_1          | 2021/11/30 11:08:01 [alert] 23#23 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
Notice: d_web_1          | 2021/11/30 11:08:01 [notice] 15#15 process 19 exited with code 0
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
```

**Comment by VBart** [comment]
It looks like a duplicate of this issue: https://github.com/nginx/unit/issues/600.
Are you using Unit 1.26.0?

**Comment by cgearing** [comment]
Yes, this is using 1.26.0 - I ran unit with debug and couldn't see any obvious extra information:
```
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, launching Unit daemon to perform initial configuration...
prod_web_1          | 2021/11/30 11:32:35 [info] 13#13 unit started
prod_web_1          | 2021/11/30 11:32:35 [info] 16#16 discovery started
prod_web_1          | 2021/11/30 11:32:35 [notice] 16#16 module: python 3.9.9 "/usr/lib/unit/modules/python3.unit.so"
prod_web_1          | 2021/11/30 11:32:35 [info] 14#14 controller started
prod_web_1          | 2021/11/30 11:32:35 [info] 18#18 router started
prod_web_1          | 2021/11/30 11:32:35 [notice] 14#14 process 16 exited with code 0
prod_web_1          | 2021/11/30 11:32:35 [info] 18#18 OpenSSL 1.1.1k  25 Mar 2021, 101010bf
prod_web_1          | {
prod_web_1          | 	"certificates": {},
prod_web_1          | 	"config": {
prod_web_1          | 		"listeners": {},
prod_web_1          | 		"applications": {}
prod_web_1          | 	}
prod_web_1          | }
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Looking for certificate bundles in /docker-entrypoint.d/...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Looking for configuration snippets in /docker-entrypoint.d/...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Applying configuration /docker-entrypoint.d/config.json
prod_web_1          | 2021/11/30 11:32:35 [info] 22#22 "fastapi" prototype started
prod_web_1          | 2021/11/30 11:32:35 [info] 23#23 "fastapi" application started
prod_web_1          | 2021/11/30 11:32:40 [info] 28#28 "fastapi" application started
prod_web_1          | 2021/11/30 11:32:41 [info] 33#33 "fastapi" application started
prod_web_1          | 2021/11/30 11:32:42 [info] 38#38 "fastapi" application started
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: OK: HTTP response status code is '200'
prod_web_1          | {
prod_web_1          | 	"success": "Reconfiguration done."
prod_web_1          | }
prod_web_1          |
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Stopping Unit daemon after initial configuration...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
prod_web_1          | 2021/11/30 11:32:43 [notice] 14#14 process 17 exited with code 0
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
prod_web_1          | 2021/11/30 11:32:44 [notice] 22#22 app process (isolated 28) exited with code 0
prod_web_1          | 2021/11/30 11:32:44 [alert] 22#22 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
prod_web_1          | 2021/11/30 11:32:44 [notice] 22#22 app process (isolated 33) exited with code 0
prod_web_1          | 2021/11/30 11:32:44 [alert] 22#22 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
prod_web_1          | 2021/11/30 11:32:44 [notice] 22#22 app process (isolated 23) exited with code 0
prod_web_1          | 2021/11/30 11:32:44 [alert] 22#22 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
prod_web_1          | 2021/11/30 11:32:44 [notice] 22#22 app process (isolated 38) exited with code 0
prod_web_1          | 2021/11/30 11:32:44 [alert] 22#22 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
prod_web_1          | 2021/11/30 11:32:44 [notice] 14#14 process 18 exited with code 0
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
prod_web_1          | /usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
```

**Comment by VBart** [comment]
It doesn't look like Unit with debug. When debug is enabled, there will be lots of `[debug]` lines in output. How do you run it? Note, that you have to change the `docker-entrypoint.sh` script, since it runs Unit in your case.

**Comment by VBart** [comment]
@cgearing Your parameters doesn't affect the command for starting Unit in `docker-entrypoint.sh`.  You can look at the script itself, it's pretty simple: https://github.com/nginx/unit/blob/master/pkg/docker/docker-entrypoint.sh#L27

Probably it needs to be fixed for respecting `unit-debug` (cc: @thresheek )

**Comment by VBart** [comment]
But, anyway, the issue with stopping Unit 1.26 is reported in #600 and fixed with https://github.com/nginx/unit/commit/2bc95990571f82ddfc685fadff4847abff4362e3, which will be released soon.

**Comment by cgearing** [comment]
Sorry @VBart my brain has finally caught up with what you're saying.

Here's a gist for the logs https://gist.github.com/cgearing/d1bbe789181c4400f5381301c9550be3 (I thought it would be too much for this thread).

**Comment by mar0x** [comment]
Thanks for debug log. I've inspected it and confirm the issue caused by the bug in SIGCHLD handler which was fixed in #600 .

In the log I was unable to find the last records from PID 16 (controller), notable `exit: 0`, however the process terminated according to `waitpid(): 16` record.

**Comment by cgearing** [comment]
I've just tried 1.26.1 and I'm fairly sure that it has fixed the issue - thank you for creating a brilliant tool - it's made developing/deploying small applications very easy!

**Comment by kkzetAM** [comment]
Hi,
I still have this problem in 1.26, 1.26.1 and 1.27 with python3.9 
`FROM nginx/unit:1.26.1-python3.9`

But, This problem occurs randomly.

`/usr/local/bin/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, launching Unit daemon to perform initial configuration...
2022/06/22 11:37:02 [warn] 12#12 Unit is running unprivileged, then it cannot use arbitrary user and group.
2022/06/22 11:37:02 [info] 12#12 unit started
2022/06/22 11:37:02 [info] 15#15 discovery started
2022/06/22 11:37:02 [notice] 15#15 module: python 3.9.6 "/usr/lib/unit/modules/python3.unit.so"
2022/06/22 11:37:02 [info] 13#13 controller started
2022/06/22 11:37:02 [notice] 13#13 process 15 exited with code 0
2022/06/22 11:37:02 [info] 17#17 router started
2022/06/22 11:37:02 [info] 17#17 OpenSSL 1.1.1k  25 Mar 2021, 101010bf
{
    "certificates": {},
    "config": {
        "listeners": {},
        "applications": {}
    }
}
/usr/local/bin/docker-entrypoint.sh: Looking for certificate bundles in /docker-entrypoint.d/...
/usr/local/bin/docker-entrypoint.sh: Uploading certificates bundle: /docker-entrypoint.d/certs/bundle.pem
/usr/local/bin/docker-entrypoint.sh: OK: HTTP response status code is '200'
{
    "success": "Certificate chain uploaded."
}
/usr/local/bin/docker-entrypoint.sh: Looking for configuration snippets in /docker-entrypoint.d/...
/usr/local/bin/docker-entrypoint.sh: Applying configuration /docker-entrypoint.d/config.json
2022/06/22 11:37:02 [info] 26#26 "fastapi" application started
2022/06/22 11:37:04 [info] 42#42 "fastapi" application started
/usr/local/bin/docker-entrypoint.sh: OK: HTTP response status code is '200'
{
    "success": "Reconfiguration done."
}
/usr/local/bin/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/...
/usr/local/bin/docker-entrypoint.sh: Stopping Unit daemon after initial configuration...
2022/06/22 11:37:06 [info] 79#79 "fastapi" application started
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
2022/06/22 11:37:06 [notice] 13#13 process 16 exited with code 0
2022/06/22 11:37:06 [warn] 42#42 [unit] #10: active request on ctx quit
2022/06/22 11:37:06 [warn] 42#42 [unit] #10: active request on ctx free
2022/06/22 11:37:06 [notice] 13#13 process 17 exited with code 0
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
2022/06/22 11:37:06 [notice] 13#13 process 26 exited with code 0
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
2022/06/22 11:37:06 [notice] 13#13 process 42 exited with code 0
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...`


`/usr/local/bin/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, launching Unit daemon to perform initial configuration...
2022/06/22 11:55:57 [warn] 11#11 Unit is running unprivileged, then it cannot use arbitrary user and group.
2022/06/22 11:55:57 [info] 11#11 unit 1.26.1 started
2022/06/22 11:55:57 [info] 13#13 discovery started
2022/06/22 11:55:57 [notice] 13#13 module: python 3.9.9 "/usr/lib/unit/modules/python3.unit.so"
2022/06/22 11:55:57 [info] 12#12 controller started
2022/06/22 11:55:57 [notice] 12#12 process 13 exited with code 0
2022/06/22 11:55:57 [info] 16#16 router started
2022/06/22 11:55:57 [info] 16#16 OpenSSL 1.1.1k  25 Mar 2021, 101010bf
{
        "certificates": {},
        "config": {
                "listeners": {},
                "applications": {}
        }
}
/usr/local/bin/docker-entrypoint.sh: Looking for certificate bundles in /docker-entrypoint.d/...
/usr/local/bin/docker-entrypoint.sh: Looking for configuration snippets in /docker-entrypoint.d/...
/usr/local/bin/docker-entrypoint.sh: Applying configuration /docker-entrypoint.d/config.json
2022/06/22 11:55:57 [info] 20#20 "fastapi" prototype started
2022/06/22 11:55:57 [info] 21#21 "fastapi" application started
/usr/local/bin/docker-entrypoint.sh: OK: HTTP response status code is '200'
{
        "success": "Reconfiguration done."
}

/usr/local/bin/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/...
/usr/local/bin/docker-entrypoint.sh: Stopping Unit daemon after initial configuration...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
2022/06/22 11:56:00 [notice] 12#12 process 15 exited with code 0
2022/06/22 11:56:00 [notice] 12#12 process 16 exited with code 0
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
2022/06/22 11:56:00 [notice] 20#20 app process (isolated 21) exited with code 0
2022/06/22 11:56:00 [alert] 20#20 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
2022/06/22 11:56:00 [notice] 12#12 process 20 exited with code 0

/usr/local/bin/docker-entrypoint.sh: Unit initial configuration complete; ready for start up...

2022/06/22 11:56:00 [warn] 1#1 Unit is running unprivileged, then it cannot use arbitrary user and group.
`
